name: Economy
version: 1.0.0
main: io.github.ulxsth.EconomyPlugin
author: ulxsth
commands:
  bal:
    aliases: [ bal, balance ]
    description: "所持金を確認します"
  add:
    aliases: [add]
    description: "プレイヤーの所持金を追加します"
  dec:
    aliases: [dec]
    description: "プレイヤーの所持金を減らします"